[project]
name = "lonk"
version = "1.2.0"
description = "A simple link shortener."
authors = [{ name = "AG DSN", email = "services@agdsn.de" }]
requires-python = ">=3.14"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "AG DSN", email = "services@agdsn.de" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Flask~=3.1.3",
    "pylint~=4.0.7",
    "SQLAlchemy~=2.0.52",
    "Flask-SQLAlchemy~=3.1.1",
    "sentry-sdk[flask]~=2.68.0",
    "psycopg~=3.3.4",
    "python-dotenv>=1.2.3",
]
